ecommerceWebMvc/Models/Classes/Departman.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace ecommerceWebMvc.Models.Classes
{
    public class Departman
    {
        [Key]
        public int DepartmanID { get; set; }
        [Column(TypeName = "VarChar")]
        [StringLength(30)]
        public string DepartmanAd { get; set; }
        public bool Durum { get; set; }
        public ICollection<Personel> Personels { get; set; }
    }
}

ecommerceWebMvc/Controllers/DepartmanController.cs
using ecommerceWebMvc.Models.Classes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ecommerceWebMvc.Controllers
{
    [Authorize]
    public class DepartmanController : Controller
    {
        // GET: Departman
        Context q = new Context();
        public ActionResult Index()
        {
            var degerler = q.Departmen.Where(x => x.Durum == true).ToList();

            return View(degerler);
        }
        [HttpGet]
        public ActionResult DepartmanEkleme()
        {

            return View();
        }


        [HttpPost]

        public ActionResult DepartmanEkleme(Departman d)
        {
            d.Durum = true;
            q.Departmen.Add(d);
            q.SaveChanges();
            return RedirectToAction("Index");


        }
        public ActionResult DepartmanSilme(int id)
        {
            var depa = q.Departmen.Find(id);
            depa.Durum = false;
            q.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult DepartmanGetirme(int id)
        {
            var dprtmn = q.Departmen.Find(id);
            return View("DepartmanGetirme", dprtmn);
        }
        public ActionResult DepartmanGuncelleme(Departman b)
        {
            var dprt = q.Departmen.Find(b.DepartmanID);
            dprt.DepartmanAd = b.DepartmanAd;
            q.SaveChanges();
            return RedirectToAction("Index");


        }
        public ActionResult DepartmanDetay(int id)
        {
            var degerler = q.Personels.Where(x => x.Departmanid == id).ToList();

            var dpt = q.Departmen.Where(x => x.DepartmanID == id).Select(y => y.DepartmanAd).FirstOrDefault();

            ViewBag.d = dpt;
            return View(degerler);

        }
        public ActionResult DepartmanPersonelSatis(int id)
        {
            var degerler = q.SatisHareketis.Where(x => x.Personelid == id).ToList();
            var per = q.Personels.Where(x => x.PersonelID == id).Select(y => y.PersonelAd + " " + y.PersonelSoyad).FirstOrDefault();
            ViewBag.dp = per;
            return View(degerler);
        }

    }
}

ecommerceWebMvc/Views/Departman/DepartmanDetay.cshtml
@using ecommerceWebMvc.Models.Classes
@model  List<Personel>
@{
    ViewBag.Title = "DepartmanDetay";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="main-container">
    <div class="pd-ltr-20 xs-pd-20-10">
        <div class="min-height-200px">
            <div class="page-header">
                <div class="row">
                    <div class="col-md-6 col-sm-12">
                        <div class="title">
                            <h4>Departman</h4>
                        </div>
                        <nav aria-label="breadcrumb" role="navigation">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item">
                                    <a href="/Home/Index">Anasayfa</a>
                                </li>
                                <li class="breadcrumb-item">
                                    <a href="/Departman/Index">Departmanlar</a>
                                </li>
                                <li class="breadcrumb-item active" aria-current="page">
                                    Departman Detay
                                </li>
                            </ol>
                        </nav>
                    </div>

                </div>
            </div>

            <div class="card-box mb-30">

                <div class="pd-20 card-box mb-30">
                    <ol class="breadcrumb mb-4">
                        <li class="breadcrumb-item active">Departman Adı: @ViewBag.d</li>
                    </ol>
                   
                    <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                    <tr>


                        
                        <th scope="col">Personel</th>
                        <th scope="col">Satışlar</th>
                        
                    </tr>
                </thead>
                <tbody>

                    @foreach (var b in Model)
                    {
                    <tr>
                        <th scope="row">@b.PersonelAd @b.PersonelSoyad</th>
                        <td><a href="/Departman/DepartmanPersonelSatis/@b.PersonelID" class="btn btn-default" style="color: white; background-color: #8FCCF8 ">Satışlar</a></td>

                    </tr>
                    }
                </tbody>
            </table>
        </div>

                </div>

            </div>
        </div>
    </div>
</div>

ecommerceWebMvc/Views/Departman/DepartmanEkleme.cshtml
@model ecommerceWebMvc.Models.Classes.Departman

@{
    ViewBag.Title = "DepartmanEkleme";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="main-container">
    <div class="pd-ltr-20 xs-pd-20-10">
        <div class="min-height-200px">
            <div class="page-header">
                <div class="row">
                    <div class="col-md-6 col-sm-12">
                        <div class="title">
                            <h4 class="text-blue h4">Departman Oluştur</h4>
                        </div>

                    </div>

                </div>
            </div>
         
            <div class="container">
                <div class="row justify-content-center mt-5">
                    <div class="col-md-4">
                        <div class="card">
                            <div class="card-body">
                                <h4 class="card-title text-blue">Departman Ekle</h4>
                                <form asp-controller="Departman" asp-action="DepartmanEkleme" method="post">
                                    <div class="form-group">
                                        @Html.LabelFor(x => x.DepartmanAd)
                                        @Html.TextBoxFor(x => x.DepartmanAd, new { @class = "form-control" })
                                    </div>
                                    <button class="btn btn-info">Kaydet</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>






          
        </div>
    </div>
</div>

ecommerceWebMvc/Views/Departman/DepartmanGetirme.cshtml
@model ecommerceWebMvc.Models.Classes.Departman


@{
    ViewBag.Title = "DepartmanGetirme";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="main-container">
    <div class="pd-ltr-20 xs-pd-20-10">
        <div class="min-height-200px">
            <div class="page-header">
                <div class="row">
                    <div class="col-md-6 col-sm-12">
                        <div class="title">
                            <h4 class="text-blue h4">Departman Güncelle</h4>
                        </div>

                    </div>

                </div>
            </div>
          
        <div class="container">
            <div class="row justify-content-center mt-5">
                <div class="col-md-4">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="card-title text-blue">Departman Güncelle</h4>
                            @if (Model.DepartmanID == 0)
                            {
                                using (Html.BeginForm("DepartmanEkleme", "Departman", FormMethod.Post))
                                {
                                    <div class="form-group">
                                        @Html.LabelFor(x => x.DepartmanAd)
                                        @Html.TextBoxFor(x => x.DepartmanAd, new { @class = "form-control" })
                                    </div>
                                    <button type="submit" class="btn btn-info">Kaydet</button>
                                }
                            }
                            else
                            {
                                using (Html.BeginForm("DepartmanGuncelleme", "Departman", FormMethod.Post))
                                {
                                    @Html.HiddenFor(x => x.DepartmanID)
                                    <div class="form-group">
                                        @Html.LabelFor(x => x.DepartmanAd)
                                        @Html.TextBoxFor(x => x.DepartmanAd, new { @class = "form-control" })
                                    </div>
                                    <button type="submit" class="btn btn-warning">Güncelle</button>
                                }
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>






        
        </div>
    </div>
</div>

ecommerceWebMvc/Views/Departman/DepartmanPersonelSatis.cshtml
@using ecommerceWebMvc.Models.Classes
@model  List<SatisHareketi>
@{
    ViewBag.Title = "DepartmanPersonelSatis";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="main-container">
    <div class="pd-ltr-20 xs-pd-20-10">
        <div class="min-height-200px">
            <div class="page-header">
                <div class="row">
                    <div class="col-md-6 col-sm-12">
                        <div class="title">
                            <h4>Departman</h4>
                        </div>
                        <nav aria-label="breadcrumb" role="navigation">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item">
                                    <a href="/Home/Index">Anasayfa</a>
                                </li>
                                <li class="breadcrumb-item">
                                    <a href="/Departman/Index">Departmanlar</a>
                                </li>
                                <li class="breadcrumb-item active" aria-current="page">
                                    Departman Personel Satış Sayfası
                                </li>
                            </ol>
                        </nav>
                    </div>

                </div>
            </div>

            <div class="card-box mb-30">

                <div class="pd-20 card-box mb-30">
                    <ol class="breadcrumb mb-4">
                        <li class="breadcrumb-item active">Personel Adı: @ViewBag.dp</li>
                    </ol>

                    <div class="table-responsive">
                        <table class="table table-striped">
                            <thead>
                                <tr>



                                    <th scope="col">Satış ID</th>
                                    <th scope="col">Ürün</th>
                                    <th scope="col">Cari</th>
                                    <th scope="col">Fiyat</th>
                                    <th scope="col">Adet</th>
                                    <th scope="col">Toplam</th>
                                    <th scope="col">Tarih</th>
                                    <th scope="col">Yazdır</th>

                                </tr>
                            </thead>
                            <tbody>

                                @foreach (var x in Model)
                                {
                                <tr>
                                    <td>@x.SatisID</td>
                                    <td>@x.Urunler.UrunAdi</td>
                                    <td>@x.Cari.CariAd @x.Cari.CariSoyad</td>
                                    <td>@x.Fiyat</td>
                                    <td>@x.Adet</td>
                                    <td>@x.ToplamTutar</td>
                                    <td>@x.Tarih</td>
                                    <td><a href="#" class="btn btn-default" style="background-color: #708EE9; color: white ">Yazdır</a></td>
                                </tr>
                                }
                            </tbody>
                        </table>
                    </div>

                </div>

            </div>
        </div>
    </div>
</div>

ecommerceWebMvc/Views/Departman/Index.cshtml
@using ecommerceWebMvc.Models.Classes
@model List<Departman>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}



<div class="main-container">
    <div class="pd-ltr-20 xs-pd-20-10">
        <div class="min-height-200px">
            <div class="page-header">
                <div class="row">
                    <div class="col-md-6 col-sm-12">
                        <div class="title">
                            <h4>Departman</h4>
                        </div>
                        <nav aria-label="breadcrumb" role="navigation">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item">
                                    <a href="/Home/Index">Anasayfa</a>
                                </li>
                                <li class="breadcrumb-item active" aria-current="page">
                                    Departmanlar
                                </li>
                            </ol>
                        </nav>
                    </div>

                </div>
            </div>
            <div class="card-box mb-30">

                <div class="pd-20 card-box mb-30">
            <div class="clearfix mb-20">
                <div class="pull-left">
                    <h4 class="text-blue h4">Departmanlar</h4>
                   
                </div>
               
            </div>
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                           

                            <th scope="col">#</th>
                            <th scope="col">Departman Adı</th>
                            <th scope="col">Sil</th>
                            <th scope="col">Güncelle</th>
                            <th scope="col">Detaylar</th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach (var b in Model)
                        {
                        <tr>
                            <th scope="row">@b.DepartmanID</th>
                            <td>@b.DepartmanAd</td>
                            <td><a href="/Departman/DepartmanSilme/@b.DepartmanID" class="btn btn-danger">Sil</a></td>

                            <td><a href="/Departman/DepartmanGetirme/@b.DepartmanID" class="btn btn-success">Güncelle</a></td>
                            <td>
                                <a href="/Departman/DepartmanDetay/@b.DepartmanID" class="btn btn-group"
                                   style="background-color: #35B8FF; color: white; ">Detaylar</a>
                            </td>
                        </tr>
                        }
                        </tbody>
                </table>
            </div>
           
        </div>

            </div>
        </div>
    </div>
</div>