ecommerceWebMvc/Models/Classes/Personel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace ecommerceWebMvc.Models.Classes
{
    public class Personel
    {
        [Key]
        public int PersonelID { get; set; }
        [Column(TypeName = "VarChar")]
        [StringLength(30)]
        [Display(Name = "Personel Adı")]
        public string PersonelAd { get; set; }
        [Column(TypeName = "VarChar")]
        [StringLength(30)]
        [Display(Name = "Personel Soyadı")]
        public string PersonelSoyad { get; set; }
        [Column(TypeName = "VarChar")]
        [StringLength(250)]
        [Display(Name = "Personel Görsel")]
        public string PersonelGorsel { get; set; }
        public bool Durum { get; set; }
        public ICollection<SatisHareketi> SatisHareketis { get; set; }
        public int Departmanid { get; set; }
        public virtual Departman Departman { get; set; }
    }
}

ecommerceWebMvc/Controllers/PersonelController.cs
using ecommerceWebMvc.Models.Classes;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ecommerceWebMvc.Controllers
{
    public class PersonelController : Controller
    {
        Context q = new Context();
        public ActionResult Index()
        {
            var deger = q.Personels.ToList();
            return View(deger);
        }
        [HttpGet]  //sayfa çalıştığında boş olarak bunu açacak
        public ActionResult PersonelEkleme()
        {
            List<SelectListItem> deger = (from x in q.Departmen.ToList()
                                          select new SelectListItem
                                          {
                                              Text = x.DepartmanAd,
                                              Value = x.DepartmanID.ToString()
                                          }).ToList();
            ViewBag.dgr1 = deger;
            return View();

        }
        [HttpPost] //butona tıklandığında çalışacak
        public ActionResult PersonelEkleme(Personel m)
        {
            if (Request.Files.Count > 0)
            {
                string dosyaadi = Path.GetFileName(Request.Files[0].FileName);
                string uzanti = Path.GetExtension(Request.Files[0].FileName);
                string yol = "/resimler/" + dosyaadi + uzanti;
                Request.Files[0].SaveAs(Server.MapPath(yol));
                m.PersonelGorsel = "/resimler/" + dosyaadi + uzanti;

            }
            q.Personels.Add(m);
            q.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult PersonelGetirme(int id)
        {
            List<SelectListItem> deger1 = (from x in q.Departmen.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.DepartmanAd,
                                               Value = x.DepartmanID.ToString()
                                           }).ToList();
            ViewBag.dgr1 = deger1;
            var prs = q.Personels.Find(id);
            return View("PersonelGetirme", prs);
        }
        public ActionResult PersonelGuncelleme(Personel p)
        {
            if (Request.Files.Count > 0)
            {
                string dosyaadi = Path.GetFileName(Request.Files[0].FileName);
                string uzanti = Path.GetExtension(Request.Files[0].FileName);
                string yol = "/resimler/" + dosyaadi + uzanti;
                Request.Files[0].SaveAs(Server.MapPath(yol));
                p.PersonelGorsel = "/resimler/" + dosyaadi + uzanti;

            }
            var pers = q.Personels.Find(p.PersonelID);
            pers.PersonelAd = p.PersonelAd;
            pers.PersonelSoyad = p.PersonelSoyad;
            pers.PersonelGorsel = p.PersonelGorsel;
            pers.Departmanid = p.Departmanid;
            q.SaveChanges();
            return RedirectToAction("Index");

        }
        public ActionResult PersonelListe()
        {
            var sorgu = q.Personels.ToList();
            return View(sorgu);

        }
    }
}

ecommerceWebMvc/Views/Personel/Index.cshtml
@using ecommerceWebMvc.Models.Classes
@model List<Personel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="main-container">
    <div class="pd-ltr-20 xs-pd-20-10">
        <div class="min-height-200px">
            <div class="page-header">
                <div class="row">
                    <div class="col-md-6 col-sm-12">
                        <div class="title">
                            <h4>Personel</h4>
                        </div>
                        <nav aria-label="breadcrumb" role="navigation">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item">
                                    <a href="/Home/Index">Anasayfa</a>
                                </li>
                                <li class="breadcrumb-item active" aria-current="page">
                                    Personel
                                </li>
                            </ol>
                        </nav>
                    </div>

                </div>
            </div>
            <div class="card-box mb-30">

                <h2 class="h4 pd-20">Personeller</h2>
                <table class="data-table table nowrap">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Görsel</th>

                            <th>Personel Adı</th>
                            <th>Personel Soyad</th>

                            <th>Departman</th>
                            <th>Güncelle</th>
                            <th>Satışlar</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var b in Model)
                        {
                            <tr>
                                <td>@b.PersonelID</td>
                                <td class="table-plus">
                                    <img src="@b.PersonelGorsel"
                                         width="70"
                                         height="70"
                                         alt="" />
                                </td>
                                
                                <td>@b.PersonelAd</td>
                                <td>@b.PersonelSoyad</td>

                                <td>@b.Departman.DepartmanAd</td>
                                <td><a href="/Personel/PersonelGetirme/@b.PersonelID" class="btn btn-success">Güncelle</a></td>
                                <td>
                                    <a href="/Departman/DepartmanPersonelSatis/@b.PersonelID" class="btn btn-group"
                                       style="background-color: #35B8FF; color: white; ">Detaylar</a>
                                </td>

                            </tr>
                        }



                    </tbody>
                </table>
            </div>

        </div>
    </div>
</div>

ecommerceWebMvc/Views/Personel/PersonelEkleme.cshtml
@model ecommerceWebMvc.Models.Classes.Personel

@{
    ViewBag.Title = "PersonelEkleme";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="main-container">
    <div class="pd-ltr-20 xs-pd-20-10">
        <div class="min-height-200px">
            <div class="page-header">
                <div class="row">
                    <div class="col-md-6 col-sm-12">
                        <div class="title">
                            <h4>Personel Ekleme</h4>
                        </div>
                        <nav aria-label="breadcrumb" role="navigation">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item">
                                    <a href="#">Anasayfa</a>
                                </li>
                                <li class="breadcrumb-item active" aria-current="page">
                                    Personel
                                </li>
                                <li class="breadcrumb-item active" aria-current="page">
                                    Personel Ekleme
                                </li>
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>

            <div class="pd-20 card-box mb-30">
                @using (Html.BeginForm("PersonelEkleme", "Personel", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    <form class="form-group" method="post">
                        <div class="form-row">
                            <div class="form-group col-md-4">
                                @Html.LabelFor(x => x.PersonelAd)
                                @Html.TextBoxFor(x => x.PersonelAd, new { @class = "form-control" })
                            </div>
                            <div class="form-group col-md-4">
                                @Html.LabelFor(x => x.PersonelSoyad)
                                @Html.TextBoxFor(x => x.PersonelSoyad, new { @class = "form-control" })
                            </div>
                            <div class="form-group col-md-4">
                                @Html.LabelFor(x => x.PersonelGorsel)
                                <input type="file" name="PersonelGorsel" />
                            </div>
                            <div class="form-group col-md-4">

                                @Html.LabelFor(x => x.Departman)
                                @Html.DropDownListFor(x => x.Departmanid, (List<SelectListItem>)ViewBag.dgr1, new
                            {
                                    @class = "form-control"
                            })
                            </div>
                            <div class="form-group col-md-4">
                                <label for="kategoriDurum">Durum</label>
                                <select id="kategoriDurum" name="Durum" class="form-control">
                                    <option value="">Lütfen bir seçenek seçin</option>
                                    <option value="true">Aktif</option>
                                    <option value="false">Pasif</option>
                                </select>
                            </div>
                        </div>
                        <button class="btn btn-primary">Kaydet</button>
                    </form>
                }

                </div>
        </div>
    </div>
</div>

ecommerceWebMvc/Views/Personel/PersonelGetirme.cshtml
@model ecommerceWebMvc.Models.Classes.Personel
@{
    ViewBag.Title = "PersonelGetirme";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="main-container">
    <div class="pd-ltr-20 xs-pd-20-10">
        <div class="min-height-200px">
            <div class="page-header">
                <div class="row">
                    <div class="col-md-6 col-sm-12">
                        <div class="title">
                            <h4>Personel Ekleme</h4>
                        </div>
                        <nav aria-label="breadcrumb" role="navigation">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item">
                                    <a href="#">Anasayfa</a>
                                </li>
                                <li class="breadcrumb-item active" aria-current="page">
                                    Personel
                                </li>
                                <li class="breadcrumb-item active" aria-current="page">
                                    Personel Güncelleme
                                </li>
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>

            <div class="pd-20 card-box mb-30">
                @using (Html.BeginForm("PersonelGuncelleme", "Personel", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    <form class="form-group" method="post">
                        <div class="form-row">
                            <div class="form-group col-md-4">
                                @Html.HiddenFor(x => x.PersonelID)
                                @Html.LabelFor(x => x.PersonelAd)
                                @Html.TextBoxFor(x => x.PersonelAd, new { @class = "form-control" })
                            </div>
                            <div class="form-group col-md-4">
                                @Html.LabelFor(x => x.PersonelSoyad)
                                @Html.TextBoxFor(x => x.PersonelSoyad, new { @class = "form-control" })
                            </div>
                            <div class="form-group col-md-4">
                                @Html.LabelFor(x => x.PersonelGorsel)
                                <input type="file" name="PersonelGorsel" />
                            </div>
                            <div class="form-group col-md-4">

                                @Html.LabelFor(x => x.Departman)
                                @Html.DropDownListFor(x => x.Departmanid, (List<SelectListItem>)ViewBag.dgr1, new
                            {
                                    @class = "form-control"
                            })
                            </div>
                            <div class="form-group col-md-4">
                                @Html.LabelFor(model => model.Durum)
                                @Html.DropDownListFor(model => model.Durum, new SelectList(new[]
                                {
                                    new SelectListItem { Text = "Aktif", Value = "true" },
                                    new SelectListItem { Text = "Pasif", Value = "false" }
                                }, "Value", "Text"), "Lütfen bir seçenek seçin", new { @class = "form-control" })
                            </div>
                        </div>
                        <button class="btn btn-primary">Güncelle</button>
                    </form>
                }

            </div>
        </div>
    </div>
</div>

ecommerceWebMvc/Views/Personel/PersonelListe.cshtml
@using ecommerceWebMvc.Models.Classes
@model List<Personel>

@{
    ViewBag.Title = "PersonelListe";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="main-container">
    <div class="pd-ltr-20 xs-pd-20-10">
        <div class="min-height-200px">
            <div class="container pd-0">
                <div class="page-header">
                    <div class="row">
                        <div class="col-md-12 col-sm-12">
                            <div class="title">
                                <h4> Personel Listesi</h4>
                            </div>
                            <nav aria-label="breadcrumb" role="navigation">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item">
                                        <a href="/Home/Index">Anasayfa</a>
                                    </li>
                                    <li class="breadcrumb-item active" aria-current="page">
                                        Personel Listesi
                                    </li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                </div>
                <div class="contact-directory-list">
                    <ul class="row">
                        @foreach (var x in Model)
                        {
                            <li class="col-xl-4 col-lg-4 col-md-6 col-sm-12">
                                <div class="contact-directory-box">
                                    <div class="contact-dire-info text-center">
                                        <div class="contact-avatar">
                                            <span>
                                                <img src=" @x.PersonelGorsel" alt="" />
                                            </span>
                                        </div>
                                        <div class="contact-name">
                                            <h4>@x.PersonelAd @x.PersonelSoyad</h4>
                                            <p>UI/UX designer</p>
                                            <div class="work text-success">
                                                <i class="ion-android-person"></i>  @x.Departman.DepartmanAd
                                            </div>
                                        </div>
                                        <div class="contact-skill">
                                            <span class="badge badge-pill">UI</span>
                                            <span class="badge badge-pill">UX</span>
                                            <span class="badge badge-pill">Photoshop</span>
                                            <span class="badge badge-pill badge-primary">+ 8</span>
                                        </div>
                                      
                                    </div>
                                    <div class="view-contact">
                                        <a href="/Departman/DepartmanPersonelSatis/@x.PersonelID" class="btn btn-sm btn-primary">
                                            Satış Geçmişi
                                        </a>
                                    </div>
                                </div>
                            </li>
                         
                        }  </ul>
                </div>
            </div>
        </div>
       </div>
</div>